/* A lexical scanner generated by flex */

/* Scanner skeleton version:
 * $Header: /home/daffy/u0/vern/flex/RCS/flex.skl,v 2.91 96/09/10 16:58:48 vern Exp $
 */

#define FLEX_SCANNER
#define YY_FLEX_MAJOR_VERSION 2
#define YY_FLEX_MINOR_VERSION 5

#include <stdio.h>


/* cfront 1.2 defines "c_plusplus" instead of "__cplusplus" */
#ifdef c_plusplus
#ifndef __cplusplus
#define __cplusplus
#endif
#endif


#ifdef __cplusplus

#include <stdlib.h>
#include <unistd.h>

/* Use prototypes in function declarations. */
#define YY_USE_PROTOS

/* The "const" storage-class-modifier is valid. */
#define YY_USE_CONST

#else	/* ! __cplusplus */

#if __STDC__

#define YY_USE_PROTOS
#define YY_USE_CONST

#endif	/* __STDC__ */
#endif	/* ! __cplusplus */

#ifdef __TURBOC__
 #pragma warn -rch
 #pragma warn -use
#include <io.h>
#include <stdlib.h>
#define YY_USE_CONST
#define YY_USE_PROTOS
#endif

#ifdef YY_USE_CONST
#define yyconst const
#else
#define yyconst
#endif


#ifdef YY_USE_PROTOS
#define YY_PROTO(proto) proto
#else
#define YY_PROTO(proto) ()
#endif

/* Returned upon end-of-file. */
#define YY_NULL 0

/* Promotes a possibly negative, possibly signed char to an unsigned
 * integer for use as an array index.  If the signed char is negative,
 * we want to instead treat it as an 8-bit unsigned char, hence the
 * double cast.
 */
#define YY_SC_TO_UI(c) ((unsigned int) (unsigned char) c)

/* Enter a start condition.  This macro really ought to take a parameter,
 * but we do it the disgusting crufty way forced on us by the ()-less
 * definition of BEGIN.
 */
#define BEGIN yy_start = 1 + 2 *

/* Translate the current start state into a value that can be later handed
 * to BEGIN to return to the state.  The YYSTATE alias is for lex
 * compatibility.
 */
#define YY_START ((yy_start - 1) / 2)
#define YYSTATE YY_START

/* Action number for EOF rule of a given start state. */
#define YY_STATE_EOF(state) (YY_END_OF_BUFFER + state + 1)

/* Special action meaning "start processing a new file". */
#define YY_NEW_FILE yyrestart( yyin )

#define YY_END_OF_BUFFER_CHAR 0

/* Size of default input buffer. */
#define YY_BUF_SIZE 16384

typedef struct yy_buffer_state *YY_BUFFER_STATE;

extern int yyleng;
extern FILE *yyin, *yyout;

#define EOB_ACT_CONTINUE_SCAN 0
#define EOB_ACT_END_OF_FILE 1
#define EOB_ACT_LAST_MATCH 2

/* The funky do-while in the following #define is used to turn the definition
 * int a single C statement (which needs a semi-colon terminator).  This
 * avoids problems with code like:
 *
 * 	if ( condition_holds )
 *		yyless( 5 );
 *	else
 *		do_something_else();
 *
 * Prior to using the do-while the compiler would get upset at the
 * "else" because it interpreted the "if" statement as being all
 * done when it reached the ';' after the yyless() call.
 */

/* Return all but the first 'n' matched characters back to the input stream. */

#define yyless(n) \
	do \
		{ \
		/* Undo effects of setting up yytext. */ \
		*yy_cp = yy_hold_char; \
		YY_RESTORE_YY_MORE_OFFSET \
		yy_c_buf_p = yy_cp = yy_bp + n - YY_MORE_ADJ; \
		YY_DO_BEFORE_ACTION; /* set up yytext again */ \
		} \
	while ( 0 )

#define unput(c) yyunput( c, yytext_ptr )

/* The following is because we cannot portably get our hands on size_t
 * (without autoconf's help, which isn't available because we want
 * flex-generated scanners to compile on their own).
 */
typedef unsigned int yy_size_t;


struct yy_buffer_state
	{
	FILE *yy_input_file;

	char *yy_ch_buf;		/* input buffer */
	char *yy_buf_pos;		/* current position in input buffer */

	/* Size of input buffer in bytes, not including room for EOB
	 * characters.
	 */
	yy_size_t yy_buf_size;

	/* Number of characters read into yy_ch_buf, not including EOB
	 * characters.
	 */
	int yy_n_chars;

	/* Whether we "own" the buffer - i.e., we know we created it,
	 * and can realloc() it to grow it, and should free() it to
	 * delete it.
	 */
	int yy_is_our_buffer;

	/* Whether this is an "interactive" input source; if so, and
	 * if we're using stdio for input, then we want to use getc()
	 * instead of fread(), to make sure we stop fetching input after
	 * each newline.
	 */
	int yy_is_interactive;

	/* Whether we're considered to be at the beginning of a line.
	 * If so, '^' rules will be active on the next match, otherwise
	 * not.
	 */
	int yy_at_bol;

	/* Whether to try to fill the input buffer when we reach the
	 * end of it.
	 */
	int yy_fill_buffer;

	int yy_buffer_status;
#define YY_BUFFER_NEW 0
#define YY_BUFFER_NORMAL 1
	/* When an EOF's been seen but there's still some text to process
	 * then we mark the buffer as YY_EOF_PENDING, to indicate that we
	 * shouldn't try reading from the input source any more.  We might
	 * still have a bunch of tokens to match, though, because of
	 * possible backing-up.
	 *
	 * When we actually see the EOF, we change the status to "new"
	 * (via yyrestart()), so that the user can continue scanning by
	 * just pointing yyin at a new input file.
	 */
#define YY_BUFFER_EOF_PENDING 2
	};

static YY_BUFFER_STATE yy_current_buffer = 0;

/* We provide macros for accessing buffer states in case in the
 * future we want to put the buffer states in a more general
 * "scanner state".
 */
#define YY_CURRENT_BUFFER yy_current_buffer


/* yy_hold_char holds the character lost when yytext is formed. */
static char yy_hold_char;

static int yy_n_chars;		/* number of characters read into yy_ch_buf */


int yyleng;

/* Points to current character in buffer. */
static char *yy_c_buf_p = (char *) 0;
static int yy_init = 1;		/* whether we need to initialize */
static int yy_start = 0;	/* start state number */

/* Flag which is used to allow yywrap()'s to do buffer switches
 * instead of setting up a fresh yyin.  A bit of a hack ...
 */
static int yy_did_buffer_switch_on_eof;

void yyrestart YY_PROTO(( FILE *input_file ));

void yy_switch_to_buffer YY_PROTO(( YY_BUFFER_STATE new_buffer ));
void yy_load_buffer_state YY_PROTO(( void ));
YY_BUFFER_STATE yy_create_buffer YY_PROTO(( FILE *file, int size ));
void yy_delete_buffer YY_PROTO(( YY_BUFFER_STATE b ));
void yy_init_buffer YY_PROTO(( YY_BUFFER_STATE b, FILE *file ));
void yy_flush_buffer YY_PROTO(( YY_BUFFER_STATE b ));
#define YY_FLUSH_BUFFER yy_flush_buffer( yy_current_buffer )

YY_BUFFER_STATE yy_scan_buffer YY_PROTO(( char *base, yy_size_t size ));
YY_BUFFER_STATE yy_scan_string YY_PROTO(( yyconst char *yy_str ));
YY_BUFFER_STATE yy_scan_bytes YY_PROTO(( yyconst char *bytes, int len ));

static void *yy_flex_alloc YY_PROTO(( yy_size_t ));
static void *yy_flex_realloc YY_PROTO(( void *, yy_size_t ));
static void yy_flex_free YY_PROTO(( void * ));

#define yy_new_buffer yy_create_buffer

#define yy_set_interactive(is_interactive) \
	{ \
	if ( ! yy_current_buffer ) \
		yy_current_buffer = yy_create_buffer( yyin, YY_BUF_SIZE ); \
	yy_current_buffer->yy_is_interactive = is_interactive; \
	}

#define yy_set_bol(at_bol) \
	{ \
	if ( ! yy_current_buffer ) \
		yy_current_buffer = yy_create_buffer( yyin, YY_BUF_SIZE ); \
	yy_current_buffer->yy_at_bol = at_bol; \
	}

#define YY_AT_BOL() (yy_current_buffer->yy_at_bol)


#define YY_USES_REJECT
typedef unsigned char YY_CHAR;
FILE *yyin = (FILE *) 0, *yyout = (FILE *) 0;
typedef int yy_state_type;
#define YY_FLEX_LEX_COMPAT
extern int yylineno;
int yylineno = 1;
extern char yytext[];


static yy_state_type yy_get_previous_state YY_PROTO(( void ));
static yy_state_type yy_try_NUL_trans YY_PROTO(( yy_state_type current_state ));
static int yy_get_next_buffer YY_PROTO(( void ));
static void yy_fatal_error YY_PROTO(( yyconst char msg[] ));

/* Done after the current pattern has been matched and before the
 * corresponding action - sets up yytext.
 */
#define YY_DO_BEFORE_ACTION \
	yytext_ptr = yy_bp; \
	yyleng = (int) (yy_cp - yy_bp); \
	yy_hold_char = *yy_cp; \
	*yy_cp = '\0'; \
	if ( yyleng + yy_more_offset >= YYLMAX ) \
		YY_FATAL_ERROR( "token too large, exceeds YYLMAX" ); \
	yy_flex_strncpy( &yytext[yy_more_offset], yytext_ptr, yyleng + 1 ); \
	yyleng += yy_more_offset; \
	yy_prev_more_offset = yy_more_offset; \
	yy_more_offset = 0; \
	yy_c_buf_p = yy_cp;

#define YY_NUM_RULES 33
#define YY_END_OF_BUFFER 34
static yyconst short int yy_acclist[707] =
    {   0,
        2,    2,   34,   28,   32,   33,   11,   32,   33,   31,
       33,   29,   32,   33,   28,   32,   33,   30,   32,   33,
       28,   32,   33,   28,   32,   33,   28,   32,   33,   28,
       32,   33,   28,   32,   33,   28,   32,   33,   28,   32,
       33,   28,   32,   33,   27,   32,   33,   11,   32,   33,
       10,   28,   32,   33,    5,   28,   32,   33,    8,   11,
       32,   33,    9,   31,   33,    6,   29,   32,   33,    5,
       28,   32,   33,    7,   30,   32,   33,    5,   28,   32,
       33,    5,   28,   32,   33,    5,   28,   32,   33,    5,
       28,   32,   33,    5,   28,   32,   33,    5,   28,   32,

       33,    5,   28,   32,   33,    5,   28,   32,   33,   27,
       32,   33,    8,   11,   32,   33,    5,   10,   28,   32,
       33,    2,   28,   32,   33,    2,   11,   32,   33,    3,
       31,   33,    2,   29,   32,   33,    2,   28,   32,   33,
        2,   30,   32,   33,    2,   28,   32,   33,    2,   28,
       32,   33,    2,   28,   32,   33,    2,   28,   32,   33,
        2,   28,   32,   33,    2,   28,   32,   33,    2,   28,
       32,   33,    2,   28,   32,   33,    2,   27,   32,   33,
        2,   11,   32,   33,    2,   10,   28,   32,   33,   28,
       11,   28,   28,   21,   28,   28,   28,   28,   28,   28,

       28,   28,   28,   28,   11,   10,   10,   28,   10,   10,
       28,    5,   28,    8,   11,    5,   28,    5,   28,    5,
       21,   28,    5,   28,    5,   28,    5,   28,    5,   28,
        5,   28,    5,   28,    5,   28,    5,   28,    5,   28,
        8,   11,    5,   10,   28,    5,   10,   28,    2,   28,
        2,    2,   11,    2,   28,    2,   28,    2,   21,   28,
        2,   28,    2,   28,    2,   28,    2,   28,    2,   28,
        2,   28,    2,   28,    2,   28,    2,   28,    2,    2,
       11,    2,   10,    2,   10,   28,    2,   10,    2,   10,
       28,    1,   28,   28,   28,   20,   28,   28,   23,   28,

       28,   28,   28,   28,   28,   28,   26,    1,   10,   28,
        1,    5,   28,    5,   28,    5,   28,    5,   20,   28,
        5,   28,    5,   23,   28,    5,   28,    5,   28,    5,
       28,    5,   28,    5,   28,    5,   28,    4,   26,    1,
        5,   10,   28,    1,    2,   28,    2,   28,    2,   28,
        2,   20,   28,    2,   28,    2,   23,   28,    2,   28,
        2,   28,    2,   28,    2,   28,    2,   28,    2,   28,
        2,   26,    1,    2,   10,   28,    1,   28,    1,   28,
       28,   28,   28,   28,   28,   28,   28,   28,    1,   10,
       28,    1,   10,    1,    5,   28,    5,   28,    5,   28,

        5,   28,    5,   28,    5,   28,    5,   28,    5,   28,
        5,   28,    5,   28,    1,    5,   10,   28,    1,    2,
       28,    1,    2,    2,   28,    2,   28,    2,   28,    2,
       28,    2,   28,    2,   28,    2,   28,    2,   28,    2,
       28,    1,    2,   10,   28,    1,    2,   10,   28,   28,
       28,   28,   28,   28,   28,   28,   28,   28,    5,   28,
        5,   28,    5,   28,    5,   28,    5,   28,    5,   28,
        5,   28,    5,   28,    5,   28,    5,   28,    2,   28,
        2,   28,    2,   28,    2,   28,    2,   28,    2,   28,
        2,   28,    2,   28,    2,   28,    2,   28,   28,   28,

       28,   28,   28,   28,   28,   28,   28,   28,    5,   28,
        5,   28,    5,   28,    5,   28,    5,   28,    5,   28,
        5,   28,    5,   28,    5,   28,    5,   28,    2,   28,
        2,   28,    2,   28,    2,   28,    2,   28,    2,   28,
        2,   28,    2,   28,    2,   28,    2,   28,   28,   22,
       28,   28,   28,   19,   28,   28,   24,   28,   28,   28,
       16,   28,    5,   28,    5,   22,   28,    5,   28,    5,
       28,    5,   19,   28,    5,   28,    5,   24,   28,    5,
       28,    5,   28,    5,   16,   28,    2,   28,    2,   22,
       28,    2,   28,    2,   28,    2,   19,   28,    2,   28,

        2,   24,   28,    2,   28,    2,   28,    2,   16,   28,
       28,   28,   28,   14,   28,   25,   28,   18,   28,   28,
        5,   28,    5,   28,    5,   28,    5,   14,   28,    5,
       25,   28,    5,   18,   28,    5,   28,    2,   28,    2,
       28,    2,   28,    2,   14,   28,    2,   25,   28,    2,
       18,   28,    2,   28,   15,   28,   28,   28,   28,    5,
       15,   28,    5,   28,    5,   28,    5,   28,    2,   15,
       28,    2,   28,    2,   28,    2,   28,   12,   28,   28,
       17,   28,    5,   12,   28,    5,   28,    5,   17,   28,
        2,   12,   28,    2,   28,    2,   17,   28,   13,   28,

        5,   13,   28,    2,   13,   28
    } ;

static yyconst short int yy_accept[334] =
    {   0,
        1,    1,    1,    1,    1,    2,    3,    4,    7,   10,
       12,   15,   18,   21,   24,   27,   30,   33,   36,   39,
       42,   45,   48,   51,   55,   59,   63,   66,   70,   74,
       78,   82,   86,   90,   94,   98,  102,  106,  110,  113,
      117,  122,  126,  130,  133,  137,  141,  145,  149,  153,
      157,  161,  165,  169,  173,  177,  181,  185,  190,  191,
      192,  193,  194,  196,  197,  198,  199,  200,  201,  202,
      203,  204,  205,  205,  206,  207,  209,  210,  212,  214,
      216,  218,  220,  223,  225,  227,  229,  231,  233,  235,
      237,  239,  241,  241,  243,  246,  249,  251,  252,  254,

      256,  258,  261,  263,  265,  267,  269,  271,  273,  275,
      277,  279,  280,  282,  284,  287,  289,  292,  294,  295,
      296,  298,  299,  301,  302,  303,  304,  305,  306,  307,
      308,  311,  314,  316,  318,  321,  323,  326,  328,  330,
      332,  334,  336,  338,  340,  344,  347,  349,  351,  354,
      356,  359,  361,  363,  365,  367,  369,  371,  373,  377,
      379,  380,  381,  382,  383,  384,  385,  386,  387,  388,
      389,  392,  394,  397,  399,  401,  403,  405,  407,  409,
      411,  413,  415,  419,  422,  424,  426,  428,  430,  432,
      434,  436,  438,  440,  442,  446,  449,  450,  451,  452,

      453,  454,  455,  456,  457,  458,  459,  461,  463,  465,
      467,  469,  471,  473,  475,  477,  479,  481,  483,  485,
      487,  489,  491,  493,  495,  497,  499,  500,  501,  502,
      503,  504,  505,  506,  507,  508,  509,  511,  513,  515,
      517,  519,  521,  523,  525,  527,  529,  531,  533,  535,
      537,  539,  541,  543,  545,  547,  549,  550,  552,  553,
      554,  556,  557,  559,  560,  561,  563,  565,  568,  570,
      572,  575,  577,  580,  582,  584,  587,  589,  592,  594,
      596,  599,  601,  604,  606,  608,  611,  612,  613,  614,
      616,  618,  620,  621,  623,  625,  627,  630,  633,  636,

      638,  640,  642,  644,  647,  650,  653,  655,  657,  658,
      659,  660,  663,  665,  667,  669,  672,  674,  676,  678,
      680,  681,  683,  686,  688,  691,  694,  696,  699,  701,
      704,  707,  707
    } ;

static yyconst int yy_ec[256] =
    {   0,
        1,    1,    1,    1,    1,    1,    1,    1,    2,    3,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    2,    4,    5,    6,    1,    1,    1,    7,    1,
        1,    1,    1,    1,    8,    1,    1,    9,    9,    9,
        9,    9,    9,    9,    9,    9,    9,    1,    1,    1,
        1,    1,    1,    1,   10,   11,   12,   13,   14,   15,
       16,   17,   18,    1,   19,   20,   21,   22,   23,   24,
        1,   25,   26,   27,   28,    1,    1,    1,   29,    1,
        1,    1,    1,    1,   30,    1,   10,   11,   12,   13,

       14,   15,   16,   17,   18,    1,   19,   20,   21,   22,
       23,   24,    1,   25,   26,   27,   28,    1,    1,    1,
       29,    1,   31,    1,   32,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,

        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1
    } ;

static yyconst int yy_meta[33] =
    {   0,
        1,    2,    3,    1,    2,    1,    2,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        2,    1
    } ;

static yyconst short int yy_base[352] =
    {   0,
        0,   31,   37,   68,   74,  105,  747,    0,  744,  748,
      748,  741,  748,  734,   95,  721,  724,  727,  717,  715,
       95,  729,  108,  121,    0,  735,  748,  748,  732,  748,
      725,  104,  712,  680,  683,  671,  669,  106,  682,  110,
      151,  129,  687,  748,    0,  181,    0,  211,  241,  271,
      301,  331,  361,  391,  421,  679,  133,  451,    0,  683,
      669,  642,    0,  635,  638,  625,  614,  605,  595,  586,
      588,  121,  106,  139,    0,  141,    0,  481,    0,  588,
      581,  558,    0,  560,  567,  557,  545,  545,  543,  549,
      541,  124,  133,  148,  159,  511,  135,    0,  552,  153,

      149,  154,  170,  179,  175,  190,  196,  184,  208,  212,
      529,  142,  194,    0,  248,    0,  555,  254,  536,  528,
        0,  534,    0,  525,  528,  526,  527,  504,  507,  748,
      255,  261,  515,  507,    0,  512,    0,  492,  484,  480,
      481,  450,  453,  748,  282,  289,  213,  217,  253,  274,
      283,  290,  291,  297,  313,  317,  325,    0,  341,  349,
        0,  447,  465,  447,  444,  447,  445,  436,  186,  440,
      368,    0,  369,  413,  432,  415,  412,  408,  412,  403,
      194,  408,  376,  380,    0,  389,  381,  302,  390,  406,
      413,  420,  573,  422,  458,    0,  387,  388,  380,  398,

      380,  374,  387,  376,  376,  373,  363,  364,  350,  369,
      347,  340,  355,  346,  347,  344,  437,  445,  452,  460,
      476,  477,  482,  481,  483,  503,  336,  345,  331,  331,
      327,  319,  315,  314,  303,  309,  299,  287,  273,  271,
      264,  260,  262,  261,  248,  260,  497,  509,  511,  517,
      537,  544,  552,  569,  551,  568,  248,    0,  243,  202,
        0,  244,    0,  251,  241,    0,  229,    0,  224,  207,
        0,  224,    0,  233,  228,    0,  584,  577,  585,  591,
      589,  596,  603,  605,  611,  610,  206,  191,  169,    0,
        0,    0,  156,  144,  156,  151,    0,    0,    0,  109,

      612,  617,  628,  626,  633,  634,  640,    0,  108,  102,
      108,    0,   92,   51,   59,  635,  651,  652,  656,    0,
       44,    0,    0,    9,    0,  657,  663,  668,    0,    0,
      672,  748,   34,  699,   33,  701,  703,  705,  707,  709,
      711,  713,  715,  717,  719,  721,  723,  725,  727,  729,
      731
    } ;

static yyconst short int yy_def[352] =
    {   0,
      332,    1,  332,    3,  332,    5,  332,  333,  332,  332,
      332,  333,  332,  333,  333,  333,  333,  333,  333,  333,
      333,  332,  332,  334,  335,  332,  332,  332,  335,  332,
      335,  335,  335,  335,  335,  335,  335,  335,  332,  332,
      336,  337,  338,  332,  338,  337,  338,  337,  337,  337,
      337,  337,  337,  337,  337,  338,  338,  339,  333,  332,
      333,  333,  333,  333,  333,  333,  333,  333,  333,  333,
      333,  333,  332,  332,  340,  334,  340,  334,  335,  332,
      335,  335,  335,  335,  335,  335,  335,  335,  335,  335,
      335,  335,  332,  332,  336,  336,   55,  338,  338,   55,

       55,   55,   55,   55,   55,   55,   55,   55,   55,   55,
       55,  338,  338,  341,  339,  341,  339,  342,  333,  333,
      333,  333,  333,  333,  333,  333,  333,  333,  333,  332,
      343,  344,  335,  335,  335,  335,  335,  335,  335,  335,
      335,  335,  335,  332,  345,  346,   55,   55,   55,   55,
       55,   55,   55,   55,   55,   55,   55,  338,  347,  342,
      348,  333,  333,  333,  333,  333,  333,  333,  333,  333,
      343,  349,  344,  335,  335,  335,  335,  335,  335,  335,
      335,  335,  345,  346,  350,   55,   55,   55,   55,   55,
       55,   55,   55,   55,  347,  351,  333,  333,  333,  333,

      333,  333,  333,  333,  333,  333,  335,  335,  335,  335,
      335,  335,  335,  335,  335,  335,   55,   55,   55,   55,
       55,   55,   55,   55,   55,   55,  333,  333,  333,  333,
      333,  333,  333,  333,  333,  333,  335,  335,  335,  335,
      335,  335,  335,  335,  335,  335,   55,   55,   55,   55,
       55,   55,   55,   55,   55,   55,  333,  333,  333,  333,
      333,  333,  333,  333,  333,  333,  335,  335,  335,  335,
      335,  335,  335,  335,  335,  335,   55,   55,   55,   55,
       55,   55,   55,   55,   55,   55,  333,  333,  333,  333,
      333,  333,  333,  335,  335,  335,  335,  335,  335,  335,

       55,   55,   55,   55,   55,   55,   55,  333,  333,  333,
      333,  335,  335,  335,  335,   55,   55,   55,   55,  333,
      333,  333,  335,  335,  335,   55,   55,   55,  333,  335,
       55,    0,  332,  332,  332,  332,  332,  332,  332,  332,
      332,  332,  332,  332,  332,  332,  332,  332,  332,  332,
      332
    } ;

static yyconst short int yy_nxt[781] =
    {   0,
        8,    9,   10,    8,   11,   12,   13,    8,    8,    8,
       14,   15,    8,   16,   17,    8,    8,    8,   18,    8,
       19,    8,   20,    8,    8,   21,    8,    8,    8,    8,
       22,    8,   23,   79,   59,  330,   24,   25,   26,   27,
       25,   28,   29,   30,   25,   25,   25,   31,   32,   25,
       33,   34,   25,   25,   25,   35,   25,   36,   25,   37,
       25,   25,   38,   25,   25,   25,   25,   39,   25,   40,
      329,  325,  324,   41,   42,   43,   44,   42,   45,   46,
       47,   42,   42,   42,   48,   49,   42,   50,   51,   42,
       42,   42,   52,   42,   53,   42,   54,   42,   42,   55,

       42,   42,   42,   42,   56,   42,   57,   63,   70,   74,
       58,   94,  323,   75,   73,   75,   83,   64,   71,   90,
      322,   72,   77,  321,   78,   77,   84,   77,  320,   91,
       98,  315,   92,   98,  113,   98,  128,  130,  114,  142,
       74,   93,   77,  129,   75,   77,  143,   77,   97,   94,
      112,   77,   77,   75,   96,   77,  146,   77,   97,   98,
       77,   97,   97,   77,  144,   77,   97,   97,  314,  313,
      312,   77,   97,  158,  147,   97,   97,   97,  311,   97,
       97,   77,   98,   97,  100,   98,  310,   98,   97,   77,
      148,  149,   97,   97,  150,  113,   97,   97,   97,  114,

      204,   97,   97,   97,  309,   97,  205,   97,  214,   97,
      153,   98,   98,   97,  215,   98,   97,   98,  151,   97,
      101,   97,   97,  152,  289,  155,  186,  154,  290,  296,
       97,   97,  308,  297,   97,   97,   97,  187,   97,   97,
       97,   98,   98,   97,  300,   98,  299,   98,  298,  116,
      295,  294,  116,  102,  116,  161,  172,  293,  161,  172,
      161,  172,  161,  103,  292,  161,   97,  161,  291,  288,
      287,   98,   98,  276,  275,   98,   97,   98,  116,   97,
      274,  273,  272,  172,  161,  172,  172,  188,  172,  271,
      185,  161,  104,  185,  270,  185,   97,   97,  269,  268,

       97,   98,   98,   97,   97,   98,   97,   98,  190,   97,
      191,  189,  172,   97,   97,   97,   97,   97,  105,  185,
       97,  267,  266,   97,  192,   97,   97,  219,   97,  265,
       97,   98,   98,  264,  263,   98,   97,   98,   97,   97,
       97,  262,  196,   97,  106,  196,  193,  196,   97,  194,
      161,   97,  261,  161,  260,  161,  259,  258,  257,  246,
      245,   98,   98,  244,  243,   98,  242,   98,  241,  172,
      161,  196,  172,  161,  172,  161,  240,  172,  239,  161,
      172,  185,  172,  107,  185,  238,  185,  237,  236,  235,
      218,   98,   98,  234,   97,   98,  233,   98,  172,  161,

      232,  231,   97,   97,   97,  230,  172,   97,  229,  228,
      185,  227,   97,   97,  108,   97,  220,  216,  217,   97,
      213,   98,   98,  212,  222,   98,   97,   98,  221,   97,
      211,  226,   97,   97,  109,   97,   97,  223,  210,   97,
      209,  208,  207,   97,  110,   97,   97,  111,   97,  206,
       97,   98,  116,  203,  117,  116,  202,  116,   97,  196,
       97,  247,  196,   97,  196,   97,  248,  250,   97,  201,
      200,   97,  199,   97,  198,   97,  197,  182,   97,  181,
      249,  116,   77,   97,  131,   77,   97,   77,  196,   97,
       97,  253,  180,  179,   97,   97,  255,  251,  254,   97,

       97,  178,   97,  252,   97,   97,   97,   97,   97,   97,
       97,   77,   77,  177,  145,   77,   97,   77,  256,  277,
       97,  278,   97,   97,   97,  176,   97,  175,  174,   97,
       97,  170,   97,  169,   97,   97,  279,   97,  168,  167,
      280,   77,   97,   97,  156,  166,  165,  164,  163,  162,
       97,  157,   97,   99,  141,   97,  116,   97,  159,  116,
       97,  116,  281,   97,   97,   97,  282,   97,  140,  139,
       97,  283,  138,  137,   97,   97,  136,  285,   97,  135,
      134,  286,   97,  133,  132,  116,   97,  224,  284,   80,
       97,   97,   97,  225,   97,   97,   97,   97,   97,   97,

       97,  127,   97,   97,   97,  126,  301,   97,   97,   97,
       97,  302,   97,  303,   97,   97,   97,  304,  306,   97,
      305,  125,   97,   97,   97,   97,   97,  307,   97,   97,
      317,   97,  124,   97,   97,   97,   97,   97,  316,   97,
       97,   97,  123,   97,  122,  318,   97,   97,   97,   97,
      121,   97,   97,   97,   97,  120,   97,   97,   97,   97,
       97,   97,  319,   97,   97,   97,   97,  119,  328,   97,
       97,  326,  118,  327,   97,   97,   97,   97,   97,   97,
       97,   97,   97,   97,   60,   97,   97,  112,   99,  331,
       93,   97,   89,   88,   97,   97,   87,   86,   97,   76,

       76,   95,   95,   97,   97,   98,   98,  115,  115,   77,
       77,  116,  116,  160,  160,  171,  171,  173,  173,  183,
      183,  184,  184,  195,  195,  161,  161,  172,  172,  185,
      185,  196,  196,   85,   82,   81,   80,   73,   69,   68,
       67,   66,   65,   62,   61,   60,  332,    7,  332,  332,
      332,  332,  332,  332,  332,  332,  332,  332,  332,  332,
      332,  332,  332,  332,  332,  332,  332,  332,  332,  332,
      332,  332,  332,  332,  332,  332,  332,  332,  332,  332
    } ;

static yyconst short int yy_chk[781] =
    {   0,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    2,  335,  333,  324,    2,    3,    3,    3,
        3,    3,    3,    3,    3,    3,    3,    3,    3,    3,
        3,    3,    3,    3,    3,    3,    3,    3,    3,    3,
        3,    3,    3,    3,    3,    3,    3,    3,    3,    4,
      321,  315,  314,    4,    5,    5,    5,    5,    5,    5,
        5,    5,    5,    5,    5,    5,    5,    5,    5,    5,
        5,    5,    5,    5,    5,    5,    5,    5,    5,    5,

        5,    5,    5,    5,    5,    5,    6,   15,   21,   23,
        6,   40,  313,   23,   73,   40,   32,   15,   21,   38,
      311,   21,   24,  310,   24,   24,   32,   24,  309,   38,
       42,  300,   38,   42,   57,   42,   72,   73,   57,   92,
       74,   93,   76,   72,   74,   76,   92,   76,   97,   94,
      112,   24,   41,   94,   41,   41,  100,   41,   97,   42,
       95,   97,  101,   95,   93,   95,  100,  102,  296,  295,
      294,   76,  101,  112,  101,  101,  100,  102,  293,  100,
      102,   41,   46,  103,   46,   46,  289,   46,  105,   95,
      103,  104,  104,  103,  105,  113,  103,  108,  105,  113,

      169,  105,  104,  106,  288,  104,  169,  108,  181,  107,
      108,   46,   48,  106,  181,   48,  106,   48,  106,  107,
       48,  109,  107,  107,  260,  110,  147,  109,  260,  270,
      148,  109,  287,  270,  109,  110,  147,  148,  110,  147,
      148,   48,   49,  148,  275,   49,  274,   49,  272,  115,
      269,  267,  115,   49,  115,  118,  131,  265,  118,  131,
      118,  131,  132,   49,  264,  132,  149,  132,  262,  259,
      257,   49,   50,  246,  245,   50,  149,   50,  115,  149,
      244,  243,  242,  145,  118,  131,  145,  150,  145,  241,
      146,  132,   50,  146,  240,  146,  151,  150,  239,  238,

      150,   50,   51,  152,  153,   51,  151,   51,  153,  151,
      154,  152,  145,  152,  153,  188,  152,  153,   51,  146,
      154,  237,  236,  154,  155,  188,  155,  188,  188,  235,
      156,   51,   52,  234,  233,   52,  155,   52,  157,  155,
      156,  232,  159,  156,   52,  159,  156,  159,  157,  157,
      160,  157,  231,  160,  230,  160,  229,  228,  227,  216,
      215,   52,   53,  214,  213,   53,  212,   53,  211,  171,
      173,  159,  171,  173,  171,  173,  210,  183,  209,  160,
      183,  184,  183,   53,  184,  208,  184,  207,  206,  205,
      187,   53,   54,  204,  187,   54,  203,   54,  171,  173,

      202,  201,  186,  189,  187,  200,  183,  187,  199,  198,
      184,  197,  186,  189,   54,  186,  189,  182,  186,  190,
      180,   54,   55,  179,  191,   55,  191,   55,  190,  190,
      178,  194,  190,  192,   55,  194,  191,  192,  177,  191,
      176,  175,  174,  192,   55,  194,  192,   55,  194,  170,
      217,   55,   58,  168,   58,   58,  167,   58,  218,  195,
      217,  217,  195,  217,  195,  219,  218,  220,  218,  166,
      165,  218,  164,  220,  163,  219,  162,  143,  219,  142,
      219,   58,   78,  220,   78,   78,  220,   78,  195,  221,
      222,  223,  141,  140,  224,  223,  225,  221,  224,  221,

      222,  139,  221,  222,  224,  223,  225,  224,  223,  225,
      247,   78,   96,  138,   96,   96,  226,   96,  226,  247,
      247,  248,  248,  247,  249,  136,  226,  134,  133,  226,
      250,  129,  248,  128,  249,  248,  249,  249,  127,  126,
      250,   96,  111,  250,  111,  125,  124,  122,  120,  119,
      251,  111,  111,   99,   91,  111,  117,  252,  117,  117,
      251,  117,  251,  251,  255,  253,  252,  252,   90,   89,
      252,  253,   88,   87,  255,  253,   86,  255,  253,   85,
       84,  256,  254,   82,   81,  117,  193,  193,  254,   80,
      278,  256,  254,  193,  256,  254,  193,  277,  279,  193,

      278,   71,  281,  278,  280,   70,  277,  277,  279,  282,
      277,  279,  281,  280,  280,  281,  283,  280,  284,  282,
      282,   69,  282,  286,  285,  301,  283,  285,  284,  283,
      302,  284,   68,  286,  285,  301,  286,  285,  301,  304,
      302,  303,   67,  302,   66,  303,  305,  306,  316,  304,
       65,  303,  304,  307,  303,   64,  305,  306,  316,  305,
      306,  316,  307,  307,  317,  318,  307,   62,  319,  319,
      326,  317,   61,  318,  317,  318,  327,  317,  318,  319,
      326,  328,  319,  326,   60,  331,  327,   56,   43,  327,
       39,  328,   37,   36,  328,  331,   35,   34,  331,  334,

      334,  336,  336,  337,  337,  338,  338,  339,  339,  340,
      340,  341,  341,  342,  342,  343,  343,  344,  344,  345,
      345,  346,  346,  347,  347,  348,  348,  349,  349,  350,
      350,  351,  351,   33,   31,   29,   26,   22,   20,   19,
       18,   17,   16,   14,   12,    9,    7,  332,  332,  332,
      332,  332,  332,  332,  332,  332,  332,  332,  332,  332,
      332,  332,  332,  332,  332,  332,  332,  332,  332,  332,
      332,  332,  332,  332,  332,  332,  332,  332,  332,  332
    } ;

static yy_state_type yy_state_buf[YY_BUF_SIZE + 2], *yy_state_ptr;
static char *yy_full_match;
static int yy_lp;
#define REJECT \
{ \
*yy_cp = yy_hold_char; /* undo effects of setting up yytext */ \
yy_cp = yy_full_match; /* restore poss. backed-over text */ \
++yy_lp; \
goto find_rule; \
}
static int yy_more_offset = 0;
static int yy_prev_more_offset = 0;
#define yymore() (yy_more_offset = yy_flex_strlen( yytext ))
#define YY_NEED_STRLEN
#define YY_MORE_ADJ 0
#define YY_RESTORE_YY_MORE_OFFSET \
	{ \
	yy_more_offset = yy_prev_more_offset; \
	yyleng -= yy_more_offset; \
	}
#ifndef YYLMAX
#define YYLMAX 8192
#endif

char yytext[YYLMAX];
char *yytext_ptr;
#line 1 "ovlfs_tab.l"
#define INITIAL 0
/******************************************************************************
 ******************************************************************************
 **
 ** COPYRIGHT (C) 1998-2003 By Arthur Naseef
 **
 ** This file is covered under the GNU General Public License Version 2.  For
 **  more information, see the file COPYING.
 **
 **
 ** FILE: ovlfs_tab.l
 **
 ** DESCRIPTION:
 **	Lexical analyzer definition for the ovlfs mount-tab file format.
 **
 **
 ** REVISION HISTORY:
 **
 ** DATE	AUTHOR		DESCRIPTION
 ** ==========	===============	==============================================
 ** 2003-06-04	ARTHUR N.	Initial Release.
 ** 2003-06-09	ARTHUR N.	Support different implementations of flex.
 **				 Boy, I miss lex.  When did simple stop being
 **				 good?
 **
 ******************************************************************************
 ******************************************************************************
 **/
#line 30 "ovlfs_tab.l"
#ident "@(#)ovlfs_tab.l	1.2	[03/07/27 22:20:37]"

#include <stdarg.h>
#include <stdio.h>
#include <stdlib.h>
#include <string.h>

#include "y.tab.h"
#include "ovlfs_tab.h"


/**
 ** FORWARD DECLARATIONS
 **/

static void	parse_spec_string(int);
static void	parse_string(char, int);



#if DEBUG_RETURN
# define do_return(x)	{ int y = (x); printf("returning %d\n", y); return y; }
#else
# define do_return(x)	return(x)
#endif

static char		*CurStr = (char *) NULL;

#ifdef YYSTYPE
extern YYSTYPE		yylval;
#else
extern long		yylval;
#endif

#ifdef FLEX

	/* Redefine the YY_INPUT() routine to read one character at a time. */
	/*  The person that thought flex needed its own buffering did not   */
	/*  appear to know that FILE POINTERS ARE ALREADY BUFFERRED. What a */
	/*  waste and hassle.                                               */

# define YY_INPUT(buf,result,max_size) \
        { \
               int c = getchar(); \
               result = (c == EOF) ? YY_NULL : (buf[0] = c, 1); \
        }
#endif



/**
 ** FUNCTION: fatal
 **
 **  PURPOSE: Display an error message and terminate the program.
 **
 ** ARGUMENTS:
 **	msg	- A format string to pass to vfprintf for the error message.
 **	...	- Arguments for the given format string.
 **/

static void	fatal (char *msg, ...)
{
	va_list	arg_list;

	va_start(arg_list, msg);

		/* Print a standard error message prefix followed by the */
		/*  given error message.                                 */

	fprintf(stderr, "Fatal error, line %d: ", yylineno);
	vfprintf(stderr, msg, arg_list);

	va_end(arg_list);

	exit(1);
}



/**
 ** FUNCTION: str_merge
 **
 **  PURPOSE: Given two strings, concatenate them into a new string and release
 **           the memory used by both arguments.
 **
 ** NOTES:
 **	- The returned string is allocated; the caller is responsible for
 **	  freeing the result.
 **/

static char	*str_merge (char *first, char *second)
{
	char	*tmp;

	tmp = (char *) malloc(strlen(first) + strlen(second) + 1);

	if ( tmp != (char *) NULL )
	{
		sprintf(tmp, "%s%s", first, second);
	}
	else
		fatal("Unable to allocate needed memory");

	free(first);
	free(second);

	return	tmp;
}

#define STRINGS 1

#define PREFILTER_ONLY 2

#line 895 "lex.yy.c"

/* Macros after this point can all be overridden by user definitions in
 * section 1.
 */

#ifndef YY_SKIP_YYWRAP
#ifdef __cplusplus
extern "C" int yywrap YY_PROTO(( void ));
#else
extern int yywrap YY_PROTO(( void ));
#endif
#endif

#ifndef YY_NO_UNPUT
static void yyunput YY_PROTO(( int c, char *buf_ptr ));
#endif

#ifndef yytext_ptr
static void yy_flex_strncpy YY_PROTO(( char *, yyconst char *, int ));
#endif

#ifdef YY_NEED_STRLEN
static int yy_flex_strlen YY_PROTO(( yyconst char * ));
#endif

#ifndef YY_NO_INPUT
#ifdef __cplusplus
static int yyinput YY_PROTO(( void ));
#else
static int input YY_PROTO(( void ));
#endif
#endif

#if YY_STACK_USED
static int yy_start_stack_ptr = 0;
static int yy_start_stack_depth = 0;
static int *yy_start_stack = 0;
#ifndef YY_NO_PUSH_STATE
static void yy_push_state YY_PROTO(( int new_state ));
#endif
#ifndef YY_NO_POP_STATE
static void yy_pop_state YY_PROTO(( void ));
#endif
#ifndef YY_NO_TOP_STATE
static int yy_top_state YY_PROTO(( void ));
#endif

#else
#define YY_NO_PUSH_STATE 1
#define YY_NO_POP_STATE 1
#define YY_NO_TOP_STATE 1
#endif

#ifdef YY_MALLOC_DECL
YY_MALLOC_DECL
#else
#if __STDC__
#ifndef __cplusplus
#include <stdlib.h>
#endif
#else
/* Just try to get by without declaring the routines.  This will fail
 * miserably on non-ANSI systems for which sizeof(size_t) != sizeof(int)
 * or sizeof(void*) != sizeof(int).
 */
#endif
#endif

/* Amount of stuff to slurp up with each read. */
#ifndef YY_READ_BUF_SIZE
#define YY_READ_BUF_SIZE 8192
#endif

/* Copy whatever the last rule matched to the standard output. */

#ifndef ECHO
/* This used to be an fputs(), but since the string might contain NUL's,
 * we now use fwrite().
 */
#define ECHO (void) fwrite( yytext, yyleng, 1, yyout )
#endif

/* Gets input and stuffs it into "buf".  number of characters read, or YY_NULL,
 * is returned in "result".
 */
#ifndef YY_INPUT
#define YY_INPUT(buf,result,max_size) \
	if ( yy_current_buffer->yy_is_interactive ) \
		{ \
		int c = '*', n; \
		for ( n = 0; n < max_size && \
			     (c = getc( yyin )) != EOF && c != '\n'; ++n ) \
			buf[n] = (char) c; \
		if ( c == '\n' ) \
			buf[n++] = (char) c; \
		if ( c == EOF && ferror( yyin ) ) \
			YY_FATAL_ERROR( "input in flex scanner failed" ); \
		result = n; \
		} \
	else if ( ((result = fread( buf, 1, max_size, yyin )) == 0) \
		  && ferror( yyin ) ) \
		YY_FATAL_ERROR( "input in flex scanner failed" );
#endif

/* No semi-colon after return; correct usage is to write "yyterminate();" -
 * we don't want an extra ';' after the "return" because that will cause
 * some compilers to complain about unreachable statements.
 */
#ifndef yyterminate
#define yyterminate() return YY_NULL
#endif

/* Number of entries by which start-condition stack grows. */
#ifndef YY_START_STACK_INCR
#define YY_START_STACK_INCR 25
#endif

/* Report a fatal error. */
#ifndef YY_FATAL_ERROR
#define YY_FATAL_ERROR(msg) yy_fatal_error( msg )
#endif

/* Default declaration of generated scanner - a define so the user can
 * easily add parameters.
 */
#ifndef YY_DECL
#define YY_DECL int yylex YY_PROTO(( void ))
#endif

/* Code executed at the beginning of each rule, after yytext and yyleng
 * have been set up.
 */
#ifndef YY_USER_ACTION
#define YY_USER_ACTION
#endif

/* Code executed at the end of each rule. */
#ifndef YY_BREAK
#define YY_BREAK break;
#endif

#define YY_RULE_SETUP \
	if ( yyleng > 0 ) \
		yy_current_buffer->yy_at_bol = \
				(yytext[yyleng - 1] == '\n'); \
	YY_USER_ACTION

YY_DECL
	{
	register yy_state_type yy_current_state;
	register char *yy_cp, *yy_bp;
	register int yy_act;

#line 169 "ovlfs_tab.l"


#line 1052 "lex.yy.c"

	if ( yy_init )
		{
		yy_init = 0;

#ifdef YY_USER_INIT
		YY_USER_INIT;
#endif

		if ( ! yy_start )
			yy_start = 1;	/* first start state */

		if ( ! yyin )
			yyin = stdin;

		if ( ! yyout )
			yyout = stdout;

		if ( ! yy_current_buffer )
			yy_current_buffer =
				yy_create_buffer( yyin, YY_BUF_SIZE );

		yy_load_buffer_state();
		}

	while ( 1 )		/* loops until end-of-file is reached */
		{
		yy_cp = yy_c_buf_p;

		/* Support of yytext. */
		*yy_cp = yy_hold_char;

		/* yy_bp points to the position in yy_ch_buf of the start of
		 * the current run.
		 */
		yy_bp = yy_cp;

		yy_current_state = yy_start;
		yy_current_state += YY_AT_BOL();
		yy_state_ptr = yy_state_buf;
		*yy_state_ptr++ = yy_current_state;
yy_match:
		do
			{
			register YY_CHAR yy_c = yy_ec[YY_SC_TO_UI(*yy_cp)];
			while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
				{
				yy_current_state = (int) yy_def[yy_current_state];
				if ( yy_current_state >= 333 )
					yy_c = yy_meta[(unsigned int) yy_c];
				}
			yy_current_state = yy_nxt[yy_base[yy_current_state] + (unsigned int) yy_c];
			*yy_state_ptr++ = yy_current_state;
			++yy_cp;
			}
		while ( yy_base[yy_current_state] != 748 );

yy_find_action:
		yy_current_state = *--yy_state_ptr;
		yy_lp = yy_accept[yy_current_state];
find_rule: /* we branch to this label when backing up */
		for ( ; ; ) /* until we find what rule we matched */
			{
			if ( yy_lp && yy_lp < yy_accept[yy_current_state + 1] )
				{
				yy_act = yy_acclist[yy_lp];
					{
					yy_full_match = yy_cp;
					break;
					}
				}
			--yy_cp;
			yy_current_state = *--yy_state_ptr;
			yy_lp = yy_accept[yy_current_state];
			}

		YY_DO_BEFORE_ACTION;

		if ( yy_act != YY_END_OF_BUFFER )
			{
			int yyl;
			for ( yyl = 0; yyl < yyleng; ++yyl )
				if ( yytext[yyl] == '\n' )
					++yylineno;
			}

do_action:	/* This label is used only to access EOF actions. */


		switch ( yy_act )
	{ /* beginning of action switch */
case 1:
YY_RULE_SETUP
#line 171 "ovlfs_tab.l"
{ prefilter(yytext + 3); }
	YY_BREAK
case 2:
YY_RULE_SETUP
#line 173 "ovlfs_tab.l"
ECHO;
	YY_BREAK
case 3:
YY_RULE_SETUP
#line 174 "ovlfs_tab.l"
printf("\n");
	YY_BREAK
case 4:
YY_RULE_SETUP
#line 176 "ovlfs_tab.l"
parse_spec_string(1);
	YY_BREAK
case 5:
YY_RULE_SETUP
#line 177 "ovlfs_tab.l"
{
					CurStr = str_merge(CurStr,
					                   strdup(yytext));
				}
	YY_BREAK
case 6:
YY_RULE_SETUP
#line 182 "ovlfs_tab.l"
parse_string('"', 1);
	YY_BREAK
case 7:
YY_RULE_SETUP
#line 183 "ovlfs_tab.l"
parse_string('\'', 1);
	YY_BREAK
case 8:
YY_RULE_SETUP
#line 185 "ovlfs_tab.l"
{
				BEGIN 0;
				yylval = (long) CurStr;
				CurStr = NULL;
				do_return(v_string);
			}
	YY_BREAK
case 9:
YY_RULE_SETUP
#line 191 "ovlfs_tab.l"
{
				BEGIN 0;
				yylval = (long) CurStr;
				CurStr = NULL;
				do_return(v_string);
			}
	YY_BREAK
case 10:
YY_RULE_SETUP
#line 198 "ovlfs_tab.l"
/* eat all comment lines */ ;
	YY_BREAK
case 11:
YY_RULE_SETUP
#line 200 "ovlfs_tab.l"
/* eat all whitespace */ ;
	YY_BREAK
case 12:
YY_RULE_SETUP
#line 202 "ovlfs_tab.l"
do_return(t_fs);
	YY_BREAK
case 13:
YY_RULE_SETUP
#line 203 "ovlfs_tab.l"
do_return(t_mnt_pt);
	YY_BREAK
case 14:
YY_RULE_SETUP
#line 204 "ovlfs_tab.l"
do_return(t_mnt_pt);
	YY_BREAK
case 15:
YY_RULE_SETUP
#line 205 "ovlfs_tab.l"
do_return(t_base_root);
	YY_BREAK
case 16:
YY_RULE_SETUP
#line 206 "ovlfs_tab.l"
do_return(t_stg_root);
	YY_BREAK
case 17:
YY_RULE_SETUP
#line 207 "ovlfs_tab.l"
do_return(t_stg_method);
	YY_BREAK
case 18:
YY_RULE_SETUP
#line 208 "ovlfs_tab.l"
do_return(t_stg_file);
	YY_BREAK
case 19:
YY_RULE_SETUP
#line 209 "ovlfs_tab.l"
do_return(t_options);
	YY_BREAK
case 20:
YY_RULE_SETUP
#line 210 "ovlfs_tab.l"
do_return(t_end);
	YY_BREAK
case 21:
YY_RULE_SETUP
#line 211 "ovlfs_tab.l"
do_return(t_cd);
	YY_BREAK
case 22:
YY_RULE_SETUP
#line 212 "ovlfs_tab.l"
do_return(t_command);
	YY_BREAK
case 23:
YY_RULE_SETUP
#line 213 "ovlfs_tab.l"
do_return(t_key);
	YY_BREAK
case 24:
YY_RULE_SETUP
#line 214 "ovlfs_tab.l"
do_return(t_special);
	YY_BREAK
case 25:
YY_RULE_SETUP
#line 215 "ovlfs_tab.l"
do_return(t_selector);
	YY_BREAK
case 26:
YY_RULE_SETUP
#line 217 "ovlfs_tab.l"
{ BEGIN STRINGS; parse_spec_string(0); }
	YY_BREAK
case 27:
YY_RULE_SETUP
#line 218 "ovlfs_tab.l"
fatal("Invalid string specifier");
	YY_BREAK
case 28:
YY_RULE_SETUP
#line 220 "ovlfs_tab.l"
{ BEGIN STRINGS; CurStr = strdup(yytext); }
	YY_BREAK
case 29:
YY_RULE_SETUP
#line 222 "ovlfs_tab.l"
{ BEGIN STRINGS; parse_string('"', 0); }
	YY_BREAK
case 30:
YY_RULE_SETUP
#line 223 "ovlfs_tab.l"
{ BEGIN STRINGS; parse_string('\'', 0); }
	YY_BREAK
case 31:
YY_RULE_SETUP
#line 225 "ovlfs_tab.l"
;
	YY_BREAK
case 32:
YY_RULE_SETUP
#line 227 "ovlfs_tab.l"
fatal("Parser internal error");
	YY_BREAK
case 33:
YY_RULE_SETUP
#line 229 "ovlfs_tab.l"
ECHO;
	YY_BREAK
#line 1322 "lex.yy.c"
			case YY_STATE_EOF(INITIAL):
			case YY_STATE_EOF(STRINGS):
			case YY_STATE_EOF(PREFILTER_ONLY):
				yyterminate();

	case YY_END_OF_BUFFER:
		{
		/* Amount of text matched not including the EOB char. */
		int yy_amount_of_matched_text = (int) (yy_cp - yytext_ptr) - 1;

		/* Undo the effects of YY_DO_BEFORE_ACTION. */
		*yy_cp = yy_hold_char;
		YY_RESTORE_YY_MORE_OFFSET

		if ( yy_current_buffer->yy_buffer_status == YY_BUFFER_NEW )
			{
			/* We're scanning a new file or input source.  It's
			 * possible that this happened because the user
			 * just pointed yyin at a new source and called
			 * yylex().  If so, then we have to assure
			 * consistency between yy_current_buffer and our
			 * globals.  Here is the right place to do so, because
			 * this is the first action (other than possibly a
			 * back-up) that will match for the new input source.
			 */
			yy_n_chars = yy_current_buffer->yy_n_chars;
			yy_current_buffer->yy_input_file = yyin;
			yy_current_buffer->yy_buffer_status = YY_BUFFER_NORMAL;
			}

		/* Note that here we test for yy_c_buf_p "<=" to the position
		 * of the first EOB in the buffer, since yy_c_buf_p will
		 * already have been incremented past the NUL character
		 * (since all states make transitions on EOB to the
		 * end-of-buffer state).  Contrast this with the test
		 * in input().
		 */
		if ( yy_c_buf_p <= &yy_current_buffer->yy_ch_buf[yy_n_chars] )
			{ /* This was really a NUL. */
			yy_state_type yy_next_state;

			yy_c_buf_p = yytext_ptr + yy_amount_of_matched_text;

			yy_current_state = yy_get_previous_state();

			/* Okay, we're now positioned to make the NUL
			 * transition.  We couldn't have
			 * yy_get_previous_state() go ahead and do it
			 * for us because it doesn't know how to deal
			 * with the possibility of jamming (and we don't
			 * want to build jamming into it because then it
			 * will run more slowly).
			 */

			yy_next_state = yy_try_NUL_trans( yy_current_state );

			yy_bp = yytext_ptr + YY_MORE_ADJ;

			if ( yy_next_state )
				{
				/* Consume the NUL. */
				yy_cp = ++yy_c_buf_p;
				yy_current_state = yy_next_state;
				goto yy_match;
				}

			else
				{
				yy_cp = yy_c_buf_p;
				goto yy_find_action;
				}
			}

		else switch ( yy_get_next_buffer() )
			{
			case EOB_ACT_END_OF_FILE:
				{
				yy_did_buffer_switch_on_eof = 0;

				if ( yywrap() )
					{
					/* Note: because we've taken care in
					 * yy_get_next_buffer() to have set up
					 * yytext, we can now set up
					 * yy_c_buf_p so that if some total
					 * hoser (like flex itself) wants to
					 * call the scanner after we return the
					 * YY_NULL, it'll still work - another
					 * YY_NULL will get returned.
					 */
					yy_c_buf_p = yytext_ptr + YY_MORE_ADJ;

					yy_act = YY_STATE_EOF(YY_START);
					goto do_action;
					}

				else
					{
					if ( ! yy_did_buffer_switch_on_eof )
						YY_NEW_FILE;
					}
				break;
				}

			case EOB_ACT_CONTINUE_SCAN:
				yy_c_buf_p =
					yytext_ptr + yy_amount_of_matched_text;

				yy_current_state = yy_get_previous_state();

				yy_cp = yy_c_buf_p;
				yy_bp = yytext_ptr + YY_MORE_ADJ;
				goto yy_match;

			case EOB_ACT_LAST_MATCH:
				yy_c_buf_p =
				&yy_current_buffer->yy_ch_buf[yy_n_chars];

				yy_current_state = yy_get_previous_state();

				yy_cp = yy_c_buf_p;
				yy_bp = yytext_ptr + YY_MORE_ADJ;
				goto yy_find_action;
			}
		break;
		}

	default:
		YY_FATAL_ERROR(
			"fatal flex scanner internal error--no action found" );
	} /* end of action switch */
		} /* end of scanning one token */
	} /* end of yylex */


/* yy_get_next_buffer - try to read in a new buffer
 *
 * Returns a code representing an action:
 *	EOB_ACT_LAST_MATCH -
 *	EOB_ACT_CONTINUE_SCAN - continue scanning from current position
 *	EOB_ACT_END_OF_FILE - end of file
 */

static int yy_get_next_buffer()
	{
	register char *dest = yy_current_buffer->yy_ch_buf;
	register char *source = yytext_ptr;
	register int number_to_move, i;
	int ret_val;

	if ( yy_c_buf_p > &yy_current_buffer->yy_ch_buf[yy_n_chars + 1] )
		YY_FATAL_ERROR(
		"fatal flex scanner internal error--end of buffer missed" );

	if ( yy_current_buffer->yy_fill_buffer == 0 )
		{ /* Don't try to fill the buffer, so this is an EOF. */
		if ( yy_c_buf_p - yytext_ptr - YY_MORE_ADJ == 1 )
			{
			/* We matched a single character, the EOB, so
			 * treat this as a final EOF.
			 */
			return EOB_ACT_END_OF_FILE;
			}

		else
			{
			/* We matched some text prior to the EOB, first
			 * process it.
			 */
			return EOB_ACT_LAST_MATCH;
			}
		}

	/* Try to read more data. */

	/* First move last chars to start of buffer. */
	number_to_move = (int) (yy_c_buf_p - yytext_ptr) - 1;

	for ( i = 0; i < number_to_move; ++i )
		*(dest++) = *(source++);

	if ( yy_current_buffer->yy_buffer_status == YY_BUFFER_EOF_PENDING )
		/* don't do the read, it's not guaranteed to return an EOF,
		 * just force an EOF
		 */
		yy_current_buffer->yy_n_chars = yy_n_chars = 0;

	else
		{
		int num_to_read =
			yy_current_buffer->yy_buf_size - number_to_move - 1;

		while ( num_to_read <= 0 )
			{ /* Not enough room in the buffer - grow it. */
#ifdef YY_USES_REJECT
			YY_FATAL_ERROR(
"input buffer overflow, can't enlarge buffer because scanner uses REJECT" );
#else

			/* just a shorter name for the current buffer */
			YY_BUFFER_STATE b = yy_current_buffer;

			int yy_c_buf_p_offset =
				(int) (yy_c_buf_p - b->yy_ch_buf);

			if ( b->yy_is_our_buffer )
				{
				int new_size = b->yy_buf_size * 2;

				if ( new_size <= 0 )
					b->yy_buf_size += b->yy_buf_size / 8;
				else
					b->yy_buf_size *= 2;

				b->yy_ch_buf = (char *)
					/* Include room in for 2 EOB chars. */
					yy_flex_realloc( (void *) b->yy_ch_buf,
							 b->yy_buf_size + 2 );
				}
			else
				/* Can't grow it, we don't own it. */
				b->yy_ch_buf = 0;

			if ( ! b->yy_ch_buf )
				YY_FATAL_ERROR(
				"fatal error - scanner input buffer overflow" );

			yy_c_buf_p = &b->yy_ch_buf[yy_c_buf_p_offset];

			num_to_read = yy_current_buffer->yy_buf_size -
						number_to_move - 1;
#endif
			}

		if ( num_to_read > YY_READ_BUF_SIZE )
			num_to_read = YY_READ_BUF_SIZE;

		/* Read in more data. */
		YY_INPUT( (&yy_current_buffer->yy_ch_buf[number_to_move]),
			yy_n_chars, num_to_read );

		yy_current_buffer->yy_n_chars = yy_n_chars;
		}

	if ( yy_n_chars == 0 )
		{
		if ( number_to_move == YY_MORE_ADJ )
			{
			ret_val = EOB_ACT_END_OF_FILE;
			yyrestart( yyin );
			}

		else
			{
			ret_val = EOB_ACT_LAST_MATCH;
			yy_current_buffer->yy_buffer_status =
				YY_BUFFER_EOF_PENDING;
			}
		}

	else
		ret_val = EOB_ACT_CONTINUE_SCAN;

	yy_n_chars += number_to_move;
	yy_current_buffer->yy_ch_buf[yy_n_chars] = YY_END_OF_BUFFER_CHAR;
	yy_current_buffer->yy_ch_buf[yy_n_chars + 1] = YY_END_OF_BUFFER_CHAR;

	yytext_ptr = &yy_current_buffer->yy_ch_buf[0];

	return ret_val;
	}


/* yy_get_previous_state - get the state just before the EOB char was reached */

static yy_state_type yy_get_previous_state()
	{
	register yy_state_type yy_current_state;
	register char *yy_cp;

	yy_current_state = yy_start;
	yy_current_state += YY_AT_BOL();
	yy_state_ptr = yy_state_buf;
	*yy_state_ptr++ = yy_current_state;

	for ( yy_cp = yytext_ptr + YY_MORE_ADJ; yy_cp < yy_c_buf_p; ++yy_cp )
		{
		register YY_CHAR yy_c = (*yy_cp ? yy_ec[YY_SC_TO_UI(*yy_cp)] : 1);
		while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
			{
			yy_current_state = (int) yy_def[yy_current_state];
			if ( yy_current_state >= 333 )
				yy_c = yy_meta[(unsigned int) yy_c];
			}
		yy_current_state = yy_nxt[yy_base[yy_current_state] + (unsigned int) yy_c];
		*yy_state_ptr++ = yy_current_state;
		}

	return yy_current_state;
	}


/* yy_try_NUL_trans - try to make a transition on the NUL character
 *
 * synopsis
 *	next_state = yy_try_NUL_trans( current_state );
 */

#ifdef YY_USE_PROTOS
static yy_state_type yy_try_NUL_trans( yy_state_type yy_current_state )
#else
static yy_state_type yy_try_NUL_trans( yy_current_state )
yy_state_type yy_current_state;
#endif
	{
	register int yy_is_jam;

	register YY_CHAR yy_c = 1;
	while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
		{
		yy_current_state = (int) yy_def[yy_current_state];
		if ( yy_current_state >= 333 )
			yy_c = yy_meta[(unsigned int) yy_c];
		}
	yy_current_state = yy_nxt[yy_base[yy_current_state] + (unsigned int) yy_c];
	yy_is_jam = (yy_current_state == 332);
	if ( ! yy_is_jam )
		*yy_state_ptr++ = yy_current_state;

	return yy_is_jam ? 0 : yy_current_state;
	}


#ifndef YY_NO_UNPUT
#ifdef YY_USE_PROTOS
static void yyunput( int c, register char *yy_bp )
#else
static void yyunput( c, yy_bp )
int c;
register char *yy_bp;
#endif
	{
	register char *yy_cp = yy_c_buf_p;

	/* undo effects of setting up yytext */
	*yy_cp = yy_hold_char;

	if ( yy_cp < yy_current_buffer->yy_ch_buf + 2 )
		{ /* need to shift things up to make room */
		/* +2 for EOB chars. */
		register int number_to_move = yy_n_chars + 2;
		register char *dest = &yy_current_buffer->yy_ch_buf[
					yy_current_buffer->yy_buf_size + 2];
		register char *source =
				&yy_current_buffer->yy_ch_buf[number_to_move];

		while ( source > yy_current_buffer->yy_ch_buf )
			*--dest = *--source;

		yy_cp += (int) (dest - source);
		yy_bp += (int) (dest - source);
		yy_current_buffer->yy_n_chars =
			yy_n_chars = yy_current_buffer->yy_buf_size;

		if ( yy_cp < yy_current_buffer->yy_ch_buf + 2 )
			YY_FATAL_ERROR( "flex scanner push-back overflow" );
		}

	*--yy_cp = (char) c;

	if ( c == '\n' )
		--yylineno;

	yytext_ptr = yy_bp;
	yy_hold_char = *yy_cp;
	yy_c_buf_p = yy_cp;
	}
#endif	/* ifndef YY_NO_UNPUT */


#ifdef __cplusplus
static int yyinput()
#else
static int input()
#endif
	{
	int c;

	*yy_c_buf_p = yy_hold_char;

	if ( *yy_c_buf_p == YY_END_OF_BUFFER_CHAR )
		{
		/* yy_c_buf_p now points to the character we want to return.
		 * If this occurs *before* the EOB characters, then it's a
		 * valid NUL; if not, then we've hit the end of the buffer.
		 */
		if ( yy_c_buf_p < &yy_current_buffer->yy_ch_buf[yy_n_chars] )
			/* This was really a NUL. */
			*yy_c_buf_p = '\0';

		else
			{ /* need more input */
			int offset = yy_c_buf_p - yytext_ptr;
			++yy_c_buf_p;

			switch ( yy_get_next_buffer() )
				{
				case EOB_ACT_LAST_MATCH:
					/* This happens because yy_g_n_b()
					 * sees that we've accumulated a
					 * token and flags that we need to
					 * try matching the token before
					 * proceeding.  But for input(),
					 * there's no matching to consider.
					 * So convert the EOB_ACT_LAST_MATCH
					 * to EOB_ACT_END_OF_FILE.
					 */

					/* Reset buffer status. */
					yyrestart( yyin );

					/* fall through */

				case EOB_ACT_END_OF_FILE:
					{
					if ( yywrap() )
						return EOF;

					if ( ! yy_did_buffer_switch_on_eof )
						YY_NEW_FILE;
#ifdef __cplusplus
					return yyinput();
#else
					return input();
#endif
					}

				case EOB_ACT_CONTINUE_SCAN:
					yy_c_buf_p = yytext_ptr + offset;
					break;
				}
			}
		}

	c = *(unsigned char *) yy_c_buf_p;	/* cast for 8-bit char's */
	*yy_c_buf_p = '\0';	/* preserve yytext */
	yy_hold_char = *++yy_c_buf_p;

	yy_current_buffer->yy_at_bol = (c == '\n');
	if ( yy_current_buffer->yy_at_bol )
		++yylineno;

	return c;
	}


#ifdef YY_USE_PROTOS
void yyrestart( FILE *input_file )
#else
void yyrestart( input_file )
FILE *input_file;
#endif
	{
	if ( ! yy_current_buffer )
		yy_current_buffer = yy_create_buffer( yyin, YY_BUF_SIZE );

	yy_init_buffer( yy_current_buffer, input_file );
	yy_load_buffer_state();
	}


#ifdef YY_USE_PROTOS
void yy_switch_to_buffer( YY_BUFFER_STATE new_buffer )
#else
void yy_switch_to_buffer( new_buffer )
YY_BUFFER_STATE new_buffer;
#endif
	{
	if ( yy_current_buffer == new_buffer )
		return;

	if ( yy_current_buffer )
		{
		/* Flush out information for old buffer. */
		*yy_c_buf_p = yy_hold_char;
		yy_current_buffer->yy_buf_pos = yy_c_buf_p;
		yy_current_buffer->yy_n_chars = yy_n_chars;
		}

	yy_current_buffer = new_buffer;
	yy_load_buffer_state();

	/* We don't actually know whether we did this switch during
	 * EOF (yywrap()) processing, but the only time this flag
	 * is looked at is after yywrap() is called, so it's safe
	 * to go ahead and always set it.
	 */
	yy_did_buffer_switch_on_eof = 1;
	}


#ifdef YY_USE_PROTOS
void yy_load_buffer_state( void )
#else
void yy_load_buffer_state()
#endif
	{
	yy_n_chars = yy_current_buffer->yy_n_chars;
	yytext_ptr = yy_c_buf_p = yy_current_buffer->yy_buf_pos;
	yyin = yy_current_buffer->yy_input_file;
	yy_hold_char = *yy_c_buf_p;
	}


#ifdef YY_USE_PROTOS
YY_BUFFER_STATE yy_create_buffer( FILE *file, int size )
#else
YY_BUFFER_STATE yy_create_buffer( file, size )
FILE *file;
int size;
#endif
	{
	YY_BUFFER_STATE b;

	b = (YY_BUFFER_STATE) yy_flex_alloc( sizeof( struct yy_buffer_state ) );
	if ( ! b )
		YY_FATAL_ERROR( "out of dynamic memory in yy_create_buffer()" );

	b->yy_buf_size = size;

	/* yy_ch_buf has to be 2 characters longer than the size given because
	 * we need to put in 2 end-of-buffer characters.
	 */
	b->yy_ch_buf = (char *) yy_flex_alloc( b->yy_buf_size + 2 );
	if ( ! b->yy_ch_buf )
		YY_FATAL_ERROR( "out of dynamic memory in yy_create_buffer()" );

	b->yy_is_our_buffer = 1;

	yy_init_buffer( b, file );

	return b;
	}


#ifdef YY_USE_PROTOS
void yy_delete_buffer( YY_BUFFER_STATE b )
#else
void yy_delete_buffer( b )
YY_BUFFER_STATE b;
#endif
	{
	if ( ! b )
		return;

	if ( b == yy_current_buffer )
		yy_current_buffer = (YY_BUFFER_STATE) 0;

	if ( b->yy_is_our_buffer )
		yy_flex_free( (void *) b->yy_ch_buf );

	yy_flex_free( (void *) b );
	}


#ifndef YY_ALWAYS_INTERACTIVE
#ifndef YY_NEVER_INTERACTIVE
#include<unistd.h>
#endif
#endif

#ifdef YY_USE_PROTOS
void yy_init_buffer( YY_BUFFER_STATE b, FILE *file )
#else
void yy_init_buffer( b, file )
YY_BUFFER_STATE b;
FILE *file;
#endif


	{
	yy_flush_buffer( b );

	b->yy_input_file = file;
	b->yy_fill_buffer = 1;

#if YY_ALWAYS_INTERACTIVE
	b->yy_is_interactive = 1;
#else
#if YY_NEVER_INTERACTIVE
	b->yy_is_interactive = 0;
#else
	b->yy_is_interactive = file ? (isatty( fileno(file) ) > 0) : 0;
#endif
#endif
	}


#ifdef YY_USE_PROTOS
void yy_flush_buffer( YY_BUFFER_STATE b )
#else
void yy_flush_buffer( b )
YY_BUFFER_STATE b;
#endif

	{
	if ( ! b )
		return;

	b->yy_n_chars = 0;

	/* We always need two end-of-buffer characters.  The first causes
	 * a transition to the end-of-buffer state.  The second causes
	 * a jam in that state.
	 */
	b->yy_ch_buf[0] = YY_END_OF_BUFFER_CHAR;
	b->yy_ch_buf[1] = YY_END_OF_BUFFER_CHAR;

	b->yy_buf_pos = &b->yy_ch_buf[0];

	b->yy_at_bol = 1;
	b->yy_buffer_status = YY_BUFFER_NEW;

	if ( b == yy_current_buffer )
		yy_load_buffer_state();
	}


#ifndef YY_NO_SCAN_BUFFER
#ifdef YY_USE_PROTOS
YY_BUFFER_STATE yy_scan_buffer( char *base, yy_size_t size )
#else
YY_BUFFER_STATE yy_scan_buffer( base, size )
char *base;
yy_size_t size;
#endif
	{
	YY_BUFFER_STATE b;

	if ( size < 2 ||
	     base[size-2] != YY_END_OF_BUFFER_CHAR ||
	     base[size-1] != YY_END_OF_BUFFER_CHAR )
		/* They forgot to leave room for the EOB's. */
		return 0;

	b = (YY_BUFFER_STATE) yy_flex_alloc( sizeof( struct yy_buffer_state ) );
	if ( ! b )
		YY_FATAL_ERROR( "out of dynamic memory in yy_scan_buffer()" );

	b->yy_buf_size = size - 2;	/* "- 2" to take care of EOB's */
	b->yy_buf_pos = b->yy_ch_buf = base;
	b->yy_is_our_buffer = 0;
	b->yy_input_file = 0;
	b->yy_n_chars = b->yy_buf_size;
	b->yy_is_interactive = 0;
	b->yy_at_bol = 1;
	b->yy_fill_buffer = 0;
	b->yy_buffer_status = YY_BUFFER_NEW;

	yy_switch_to_buffer( b );

	return b;
	}
#endif


#ifndef YY_NO_SCAN_STRING
#ifdef YY_USE_PROTOS
YY_BUFFER_STATE yy_scan_string( yyconst char *yy_str )
#else
YY_BUFFER_STATE yy_scan_string( yy_str )
yyconst char *yy_str;
#endif
	{
	int len;
	for ( len = 0; yy_str[len]; ++len )
		;

	return yy_scan_bytes( yy_str, len );
	}
#endif


#ifndef YY_NO_SCAN_BYTES
#ifdef YY_USE_PROTOS
YY_BUFFER_STATE yy_scan_bytes( yyconst char *bytes, int len )
#else
YY_BUFFER_STATE yy_scan_bytes( bytes, len )
yyconst char *bytes;
int len;
#endif
	{
	YY_BUFFER_STATE b;
	char *buf;
	yy_size_t n;
	int i;

	/* Get memory for full buffer, including space for trailing EOB's. */
	n = len + 2;
	buf = (char *) yy_flex_alloc( n );
	if ( ! buf )
		YY_FATAL_ERROR( "out of dynamic memory in yy_scan_bytes()" );

	for ( i = 0; i < len; ++i )
		buf[i] = bytes[i];

	buf[len] = buf[len+1] = YY_END_OF_BUFFER_CHAR;

	b = yy_scan_buffer( buf, n );
	if ( ! b )
		YY_FATAL_ERROR( "bad buffer in yy_scan_bytes()" );

	/* It's okay to grow etc. this buffer, and we should throw it
	 * away when we're done.
	 */
	b->yy_is_our_buffer = 1;

	return b;
	}
#endif


#ifndef YY_NO_PUSH_STATE
#ifdef YY_USE_PROTOS
static void yy_push_state( int new_state )
#else
static void yy_push_state( new_state )
int new_state;
#endif
	{
	if ( yy_start_stack_ptr >= yy_start_stack_depth )
		{
		yy_size_t new_size;

		yy_start_stack_depth += YY_START_STACK_INCR;
		new_size = yy_start_stack_depth * sizeof( int );

		if ( ! yy_start_stack )
			yy_start_stack = (int *) yy_flex_alloc( new_size );

		else
			yy_start_stack = (int *) yy_flex_realloc(
					(void *) yy_start_stack, new_size );

		if ( ! yy_start_stack )
			YY_FATAL_ERROR(
			"out of memory expanding start-condition stack" );
		}

	yy_start_stack[yy_start_stack_ptr++] = YY_START;

	BEGIN(new_state);
	}
#endif


#ifndef YY_NO_POP_STATE
static void yy_pop_state()
	{
	if ( --yy_start_stack_ptr < 0 )
		YY_FATAL_ERROR( "start-condition stack underflow" );

	BEGIN(yy_start_stack[yy_start_stack_ptr]);
	}
#endif


#ifndef YY_NO_TOP_STATE
static int yy_top_state()
	{
	return yy_start_stack[yy_start_stack_ptr - 1];
	}
#endif

#ifndef YY_EXIT_FAILURE
#define YY_EXIT_FAILURE 2
#endif

#ifdef YY_USE_PROTOS
static void yy_fatal_error( yyconst char msg[] )
#else
static void yy_fatal_error( msg )
char msg[];
#endif
	{
	(void) fprintf( stderr, "%s\n", msg );
	exit( YY_EXIT_FAILURE );
	}



/* Redefine yyless() so it works in section 3 code. */

#undef yyless
#define yyless(n) \
	do \
		{ \
		/* Undo effects of setting up yytext. */ \
		yytext[yyleng] = yy_hold_char; \
		yy_c_buf_p = yytext + n; \
		yy_hold_char = *yy_c_buf_p; \
		*yy_c_buf_p = '\0'; \
		yyleng = n; \
		} \
	while ( 0 )


/* Internal utility routines. */

#ifndef yytext_ptr
#ifdef YY_USE_PROTOS
static void yy_flex_strncpy( char *s1, yyconst char *s2, int n )
#else
static void yy_flex_strncpy( s1, s2, n )
char *s1;
yyconst char *s2;
int n;
#endif
	{
	register int i;
	for ( i = 0; i < n; ++i )
		s1[i] = s2[i];
	}
#endif

#ifdef YY_NEED_STRLEN
#ifdef YY_USE_PROTOS
static int yy_flex_strlen( yyconst char *s )
#else
static int yy_flex_strlen( s )
yyconst char *s;
#endif
	{
	register int n;
	for ( n = 0; s[n]; ++n )
		;

	return n;
	}
#endif


#ifdef YY_USE_PROTOS
static void *yy_flex_alloc( yy_size_t size )
#else
static void *yy_flex_alloc( size )
yy_size_t size;
#endif
	{
	return (void *) malloc( size );
	}

#ifdef YY_USE_PROTOS
static void *yy_flex_realloc( void *ptr, yy_size_t size )
#else
static void *yy_flex_realloc( ptr, size )
void *ptr;
yy_size_t size;
#endif
	{
	/* The cast to (char *) in the following accommodates both
	 * implementations that use char* generic pointers, and those
	 * that use void* generic pointers.  It works with the latter
	 * because both ANSI C and C++ allow castless assignment from
	 * any pointer type to void*, and deal with argument conversions
	 * as though doing an assignment.
	 */
	return (void *) realloc( (char *) ptr, size );
	}

#ifdef YY_USE_PROTOS
static void yy_flex_free( void *ptr )
#else
static void yy_flex_free( ptr )
void *ptr;
#endif
	{
	free( ptr );
	}

#if YY_MAIN
int main()
	{
	yylex();
	return 0;
	}
#endif
#line 229 "ovlfs_tab.l"



/**
 ** NOTES:
 **	- parse_string and parse_spec_string are placed here with forward
 **	  declarations above to prevent warnings regarding input's type.
 **/

/**
 ** FUNCTION: parse_string
 **
 **  PURPOSE: Given that the specified quote was found on input as the start of
 **           a string, parse the entire string and store in memory.
 **
 ** ARGUMENTS:
 **	quote	- The quote character to search for as the end of the string.
 **		  This character can be placed in the string by escaping it
 **		  with the backslash character.
 **
 **	merge	- Specify whether this string must be merged with the existing
 **		  value or this is a new string result.
 **/

static void	parse_string (char quote, int merge_ind)
{
	char	quoted_str_buf[4096];
	int	pos;
	int	one_char;
	int	start_line;
	char	*result;
	int	escaped;

	start_line = yylineno;

	pos = -1;
	escaped = 0;
	result = (char *) NULL;

		/* Continue reading input until the end of string is found. */

	do
	{
		pos++;

		one_char = input();

		if ( one_char == 0 )
		{
			fatal("file ends within the string constant starting "
			      "on line %d", start_line);
		}

			/* If the character is the backslash, take the next */
			/*  character as is.                                */

		if ( one_char == '\\' )
		{
				/* Read over the backslash. */

			one_char = input();

			if ( one_char == 0 )
			{
				fatal("file ends within the string constant "
				      "starting on line %d", start_line);
			}

			quoted_str_buf[pos] = one_char;

			escaped = 1;
		}
		else
		{
				/* If the character is the quote, close the */
				/*  string; otherwise, just add it.         */

			if ( one_char == quote )
				quoted_str_buf[pos] = '\0';
			else
				quoted_str_buf[pos] = one_char;

			escaped = 0;
		}

			/* If the input buffer has filled up, copy it into   */
			/*  the result and reset our position in the buffer. */

		if ( pos == ( sizeof(quoted_str_buf) - 2 ) )
		{
			quoted_str_buf[sizeof(quoted_str_buf) - 1] = '\0';

			if ( result == (char *) NULL )
				result = strdup(quoted_str_buf);
			else
				result = str_merge(result, quoted_str_buf);

			if ( result == (char *) NULL )
				fatal("unable to allocate needed memory");

			pos = -1;
		}
	}
	while ( ( one_char != quote ) || escaped );


		/* Add the contents of the buffer to the result, unless the */
		/*  buffer is currently empty.                              */

	if ( pos > 0 )
	{
		if ( result == (char *) NULL )
			result = strdup(quoted_str_buf);
		else
			result = str_merge(result, quoted_str_buf);

		if ( result == (char *) NULL )
			fatal("unable to allocate needed memory");
	}

	if ( result == (char *) NULL )
	{
			/* Empty string on input. */

		if ( merge_ind )
			;		/* Just leave it alone :) */
		else
		{
			CurStr = malloc(1);

			if ( CurStr != (char *) NULL )
				CurStr[0] = '\0';
		}
	}
	else
	{
		if ( merge_ind )
			CurStr = str_merge(CurStr, result);
		else
			CurStr = result;
	}

	if ( CurStr == (char *) NULL )
		fatal("unable to allocate needed memory");
}



/**
 ** FUNCTION: parse_spec_string
 **
 **  PURPOSE: Given that a special string's size specifier has been found on
 **           input, read the string into memory.
 **
 ** ARGUMENTS:
 **	merge	- Indicate whether this string is a new result string or must
 **		  be merged with the existing result string.
 **/

static void	parse_spec_string (int merge_ind)
{
	int	start_line = yylineno;
	int	cur;
	int	start_len;
	int	len;
	int	one_char;
	char	*ptr;
	char	*result;


		/* Use sscanf() to extract the length. */

	if ( sscanf(yytext, "{%d}", &len) != 1 )
	{
		fatal("Internal parser error - unable to determine string "
		      "length");
	}

	if ( len <= 0 )		/* should never be < 0, but be safe */
	{
			/* The string is the empty string.  Don't try to */
			/*  use strdup("") because many strdup's fail on */
			/*  the empty string.                            */

		result = (char *) malloc(1);

		if ( result != (char *) NULL )
			result[0] = '\0';
		else
			fatal("Unable to allocate needed memory");
	}
	else
	{
			/* Allocate the memory to hold the string and the */
			/*  terminating null byte.                        */

		result = (char *) malloc(len + 1);

		if ( result == (char *) NULL )
			fatal("Unable to allocate needed memory");


		ptr = result;
		start_len = len;	/* for error message, if needed */

			/* Read into the result buffer until the entire */
			/*  string has been read.                       */

		while ( len-- )
		{
			one_char = input();

			if ( one_char == 0 )
			{
				fatal("End of file in string starting on "
				      "line %d, length %d", start_line, len);
			}

			ptr[0] = one_char;
			ptr++;
		}

		result[len] = '\0';	/* Make sure it is null terminated */
	}

	if ( merge_ind )
		CurStr = str_merge(CurStr, result);
	else
		CurStr = result;
}



/**
 ** FUNCTION: prefilter_only_mode
 **/

void	prefilter_only_mode ()
{
	BEGIN PREFILTER_ONLY;
}
